src/index.d.ts

https://arethetypeswrong.github.io/?p=preact-iso%402.3.1
Importing from the bare module results in broken types with the `NodeNext` module resolution, as TS expects `.js` extensions to refer to the other `.d.ts` types.

fix: TS types w/ `NodeNext` module resolution

---

package.json

RTS is only used for the prerender export so it should be optional.

fix: Mark rts as an optional peer dependency

---

src/router.d.ts
src/router.js
test/router.test.js

Implementation https://github.com/preactjs/preact-iso/issues/6#issuecomment-1929966569
```ts
const loc = useLocation()
loc.route('/', true)
````
---
Strange, I didn't find the formatting configuration, maybe [this](https://github.com/preactjs/preact/blob/a3f7c33693f18d8d51e18478a9cc0d02f74a11d1/package.json#L191-L195) is used?

feat: Support for the replace parameter in useLocation().route

---

package.json
src/prerender.d.ts
src/prerender.js
yarn.lock

ref https://github.com/preactjs/wmr/issues/965#issuecomment-2005176575
- Update `preact-render-to-string` v6.4.0
- Because renderToStringAsync was exported from this version
- Replace `renderToString` to `renderToStringAsync`

Replace `renderToString` to `renderToStringAsync`

---

package.json
src/prerender.js

Fixes: https://github.com/preactjs/preset-vite/issues/117
Vite's pretty weird here; when RTS isn't installed...
- and the default export is used, it'll have no problem
- and a wildcard import is used, it'll emit a warning
- and a named import is used, it'll fall right over and fail to build (as the linked issue shows)
Alternatively, maybe it's worth reverting making RTS an optional peer dep altogether as there's also [this funky issue](https://github.com/vitejs/vite/discussions/15725)
Edit: Worth looking at in the next major, maybe keep `/prerender` as the only subpath export. I don't want to break anything now though.

fix: RTS peer dep w/ Vite

---

src/router.js
test/router.test.js

The current setup for `onLoadEnd` is problematic as we also need to be able to trigger it without route change, such as a page load/refresh. [preact-www](https://github.com/preactjs/preact-www/blob/89f74cb4a416b2679d7ed80fce185f2e614bf02c/src/components/routes.jsx#L13-L19) displays this issue and is locked to an older version because of this, as the loading bar will run from initial page load until the user navigates elsewhere.
This adds tests for `onLoadStart`/`onLoadEnd`/`onRouteChange` for page load & navigation, as well as a test to ensure we haven't regressed to calling `onLoadEnd` on every render, which was [the reason](https://github.com/preactjs/wmr/issues/836) for this setup.

fix: Ensure `loadEnd` is called even without route navigation

---

src/router.js
test/router.test.js

While debugging an issue on my portfolio I noticed that we wouldn't carry over the flags which means that we would lose out on hydration as soon as a lazy boundary resolves.

ensure we carry over suspense

---

src/router.js
test/router.test.js

Avoids swapping out component if the route hasn't changed. I remember seeing Jason ran into this on [Mastodawn](https://github.com/developit/mastodawn/blob/main/patches/preact-iso%2B2.3.1.patch), modified his implementation a bit for here.
I'm not 100% sure of this implementation, but the issue I'm looking to fix is that same-component navigations end up dropping the previous for the new which can be pretty wasteful & slow. _I believe_ diffing should win out for same-component routes more often than not, which is the main change here.
This is especially bad on the Preact docs site, where navigating via the sidebar replaces the entire page (minus the header) as we have a rather "fat" routing setup.

fix: Ensure same-component routes are rerendered rather than swapped

---

src/router.d.ts

fix: change type of `Router` children to nested `VNode` array

---

src/router.js
test/router.test.js

Remove trailing slashes but ensure that a single '/' is present.

feat(router): remove all trailing slashes for path

---

src/prerender.d.ts
src/prerender.js
test/location-stub.test.js

While a user can pass a `url` prop to `LocationProvider` (our types don't support this though), without this location stub, the router will not work during SSR as it unconditionally tries to access `location.origin`:
https://github.com/preactjs/preact-iso/blob/2398d3b824af7ff445bf9337082ad9ed523415b5/src/router.js#L72
I'm generally in favor of pushing the `location` stub anyhow, it's far more robust in allowing client-side libs to work properly, hence, making it available here for any using the router (but using their own SSR impl). I don't think passing the URL prop to components is a great pattern that we should fix or support really, but that's just me.

feat: Add `location` stub utility

---

package.json
src/internal.d.ts
src/router.d.ts
src/router.js

No longer does my editor light up like a Christmas tree for daring to open up the source for our router 😄

chore: Add some types to router, rename a couple vars

---

web-test-runner.config.js

https://github.com/preactjs/preact-iso/pull/37#discussion_r1730313791 -- failures aren't picked up correctly at the moment, forcing users to wait for timeouts. Default is `120000` (2 minutes) which is excessive for our suite as it should take less than ~5s.

test: Reduce wtr timeout limit

---

package-lock.json
package.json
test/router.test.js

(Adding here for posterity)
There's a few failing checks regarding currently mounted routes being re-invoked during a suspense nav due to https://github.com/preactjs/preact/commit/f1eed0e8711a18a12119d7ba5bfe78468d76eb57
As this is how context should normally work, we're going to call it okay for now and move on.

test: Fix tests for Preact > 10.16

---

README.md
src/lazy.d.ts
src/lazy.js
test/lazy.test.js

Still need to figure out the right song & dance for sinon to play nice, but would allow for easier preloading.
```jsx
import { render } from 'preact';
import { LocationProvider, Router, Route, lazy } from 'preact-iso';
const NotFound = lazy(() => import('./pages/_404.jsx'));
function Home() {
return (
<a href="/404" onMouseOver={() => NotFound.preload()}>
Not Found -- Hover me to preload `NotFound`!
</a>
);
}
function App() {
return (
<LocationProvider>
<Router>
<Route path="/" component={Home} />
<Route default component={NotFound} />
</Router>
</LocationProvider>
)
}
render(<App />, document.getElementById('app'));
```

feat: Add `preload()` method to `lazy`

---

README.md
src/router.d.ts
src/router.js
test/router.test.js

Closes #34
Allows users to opt-out of link interception, setting a string & regexp scope that intercepts should be limited to, e.g., `<LocationProvider scope="/app">` will ignore clicks to `/site`.

feat: Adds `scope` prop to `LocationProvider`, limiting link intercepts

---

src/router.js

Resolves https://github.com/preactjs/preact-iso/issues/46

Add null check for link before usage

---

README.md
src/router.js
test/node/router-match.test.js

Whilst https://github.com/preactjs/wmr/commit/d503514743da838f086d5760fbc62144f93fc774 added a test entry for `/:x*` paths, unfortunately it copied the test block for optional params (`/:x?`) and only updated the test name -- the actual test cases were duplicates that didn't ensure what they were meant to.
This PR therefore corrects that and adds proper tests, but also ensures optional params become `undefined`, rather than empty strings, to match the behavior of `/:x?` in the case of the param not being set. I'd call this non-breaking as the previous behavior isn't correct or consistent and any falsy check will still fail all the same.

fix: Wildcard splat/rest param matches should return `undefined` instead of empty strings

---

src/router.d.ts

This change ensures the user sets either `path` or `default` for a route, but never both.
Previously, the types erroneously allowed you to set neither &/or both; setting neither made it a dead route, never to be used, and setting both is simply redundant.
---
TS's error message isn't great, if the user sets neither, they'll be met with the following which only mentions the latter half of the XOR:
```
Type '{ component: () => Element; }' is not assignable to type 'IntrinsicAttributes & (RouteProps<{ component: () => Element; }> & Partial<{ component: () => Element; }>)'.
Type '{ component: () => Element; }' is not assignable to type 'IntrinsicAttributes & { path?: never; default: boolean; } & { component: AnyComponent<{ component: () => Element; }>; } & Partial<{ component: () => Element; …
```

feat: Switch routable props type over to an xor

---

src/hydrate.d.ts
src/hydrate.js

https://github.com/preactjs/preact/pull/3863 gave us a nicer `parent` type for core, but that never made its way here. We can just reuse `hydrates` type here from now on.

fix: Hydrate types

---

src/hydrate.d.ts

Fixes mistake in #51 (didn't mean to merge that one so early, got confused between PRs).
`parent` is an optional param here, falling back to `document.body`, so we can't use core's `hydrate` type as it is not optional there.

fix: Hydrate parent param type

---

src/lazy.js
test/lazy.test.js

Re: https://github.com/preactjs/preact-www/pull/1223
Seems reasonable enough to me to match `preact/compat`'s behavior here w/ forwarding from `lazy()`.

feat: Forward refs with `lazy()`

---

src/router.js

No functional changes here.
#12 refactored things so that we weren't using the return value of the `useMemo`, figure we can reuse it for `routeChanged` instead of having it as a separate ref.

refactor: Simplify `routeChanged` a bit

---

src/lazy.js

I think this is the issue behind the crash, the ref forwarding is expected to fail as we don't stop on vnodes anymore.
https://github.com/preactjs/ecosystem-ci/actions/runs/13334317934/job/37245956180

Set _excess in preparation for v11

---

package-lock.json
package.json
test/lazy.test.js
test/router.test.js
test/setup.js

Was about to give up on `@web/test-runner` when I remembered our custom karma serializer from the Preact repo -- this works much, much better and avoids those awful lock-ups WTR would cause when console debugging DOM nodes or sinon call histories.
I did naively copy the full impl from Preact, some of it might not be needed today but we can iterate on it later.

test: Add custom serializer for WTR

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Same as those we have in the Preact repo, but switches the Stackblitz template to one with routing & emphasizes that reproductions are necessary.

chore: Add basic issue templates to repo

---

src/router.js
test/router.test.js

Similar-ish to #69, #12 seems to cause a lot of unnecessary renders which @sbesh91 and I have been working out.
Not sure it's ideal but covers the simple cases anyhow. For the more complex, see comment below I suppose?

fix: Memoize route component to avoid double render for incoming async routes

---

test/router.test.js

Not an issue per se, but I noticed we have a bunch of extraneous `sleep()` calls in our test suite. In a couple cases the tests are a bit less clear due to the timings, as it'd make you think the test needed to wait for something when in reality the `sleep` is entirely superfluous.

test: Minor clean up of router test suite

---

src/router.js
test/router.test.js

Router should now be able to find <a> tags within open shadow DOMs.
This is a fix for #4.

fix: Resolve issue with shadow DOM

---

src/router.js
test/router.test.js

chore: Throw a clear error when the LocationProvider is missing

---

jsconfig.json
src/internal.d.ts
src/router.d.ts

Partial fix for #94
`jsconfig.json` defaults to enabling `skipLibCheck` so these errors wouldn't surface previously. Poor default, IMO, surprised me quite a few times now.

fix: Type errors in Router declaration file

---

package-lock.json
package.json

Looks to be breaking our [ecosystem CI](https://github.com/preactjs/ecosystem-ci/actions/runs/17161319973/job/48691339941), the version of RTS in our lockfile here doesn't accept v11 so it'll need a bump to avoid Preact copies.

chore: Bump RTS devDep for v11

---

README.md
polyglot-utils/.gitignore
polyglot-utils/README.md
polyglot-utils/go/README.md
polyglot-utils/go/go.mod
polyglot-utils/go/preact_iso_url_pattern.go
polyglot-utils/go/preact_iso_url_pattern_test.go
polyglot-utils/php/README.md
polyglot-utils/php/preact-iso-url-pattern.php
polyglot-utils/php/test_preact_iso_url_pattern.php
polyglot-utils/python/README.md
polyglot-utils/python/preact_iso_url_pattern.py
polyglot-utils/python/test_preact_iso_url_pattern.py
polyglot-utils/ruby/README.md
polyglot-utils/ruby/preact-iso-url-pattern.rb
polyglot-utils/ruby/test_preact_iso_url_pattern.rb
polyglot-utils/run_tests.sh
test/node/router-match.test.js

Implemented router's URL matching logic in multiple (non-JS) languages. Since those languages cannot do SSR / prerendering without a JS engine, they can still do simpler optimizations. Use cases in mind:
- Preloading of static assets (JS, CSS, images, icons)
- Early return of 404 page
- Light SEO: e.g. Move page title tag info etc into a client-side routes file, but yet have it in the HTML loaded from server

Implemented router's URL matching logic in multiple (non-JS) languages
